import { useEffect, useState } from "react";
import "./App.css";

// ============================================================
// BACKEND API
// ============================================================

const API_URL = "https://jobmatch-ai-backend-qot6.onrender.com";

const AUTO_REFRESH_INTERVAL_MS = 5 * 60 * 1000; // 5 minutes

// ============================================================
// ABOUT DETAILS
// ============================================================

const ABOUT_DETAILS = {
  resume: {
    icon: "📄",
    title: "Resume Analysis",
    summary:
      "JobMatch AI reads your PDF resume and uses AI to understand your background — not just keyword matching.",
    points: [
      "Extracts your skills, programming languages, frameworks and tools",
      "Identifies your education history and CGPA/percentage if listed",
      "Pulls out every project with its technologies and description",
      "Classifies your experience level (Fresher, Junior, Mid, Senior)",
      "Builds a professional summary based strictly on what's in your resume",
    ],
  },

  matching: {
    icon: "🎯",
    title: "Smart Job Matching",
    summary:
      "Your extracted skills are compared against live job postings to calculate a weighted compatibility score.",
    points: [
      "Fetches real, live job listings matched to your recommended roles",
      "Compares your skills against each job's required skills",
      "Weights core skills like Python, ML and React higher than general tools",
      "Ranks every job by match percentage, highest first",
      "Shows exactly which skills you match and which ones you're missing",
    ],
  },

  gaps: {
    icon: "📊",
    title: "Skill Gap Detection",
    summary:
      "For every job you're matched with, JobMatch AI shows the specific skills standing between you and a stronger match.",
    points: [
      "Compares your current skill set against in-demand role requirements",
      "Surfaces the most impactful missing skills first",
      "Helps you prioritize what to learn next instead of guessing",
      "Updates automatically every time you upload a new resume version",
    ],
  },

  roadmap: {
    icon: "🗺️",
    title: "Career Roadmap",
    summary:
      "A step-by-step, personalized plan generated by AI based on your resume and career goals.",
    points: [
      "Moves from foundations → DSA → development → projects → deployment",
      "Ends with interview preparation and job application guidance",
      "Tailored to whether you're a fresher, student, or early-career developer",
      "Practical and actionable — not generic advice",
    ],
  },
};

// ============================================================
// APP
// ============================================================

function App() {
  // ============================================================
  // STATE
  // ============================================================

  const [backendStatus, setBackendStatus] = useState("Checking...");

  const [selectedFile, setSelectedFile] = useState(null);
  const [uploading, setUploading] = useState(false);

  const [result, setResult] = useState(null);

  const [jobs, setJobs] = useState([]);
  const [loadingJobs, setLoadingJobs] = useState(false);
  const [lastUpdated, setLastUpdated] = useState(null);

  const [activePage, setActivePage] = useState("home");

  const [selectedJob, setSelectedJob] = useState(null);
  const [selectedAbout, setSelectedAbout] = useState(null);

  const [searchTerm, setSearchTerm] = useState("");
  const [locationTerm, setLocationTerm] = useState("");
  const [jobType, setJobType] = useState("All");

  const [error, setError] = useState("");

  // ============================================================
  // BACKEND HEALTH CHECK
  // ============================================================

  useEffect(() => {
    const checkBackend = async () => {
      try {
        const response = await fetch(`${API_URL}/api/health`);

        if (!response.ok) {
          throw new Error("Backend unavailable");
        }

        const data = await response.json();

        setBackendStatus(data.status || "healthy");
      } catch (err) {
        console.error("Backend health check failed:", err);
        setBackendStatus("offline");
      }
    };

    checkBackend();
  }, []);

  // ============================================================
  // LOAD JOBS
  // ============================================================

  const loadJobs = async (
    queryOverride = "",
    locationOverride = ""
  ) => {
    setLoadingJobs(true);

    try {
      const params = new URLSearchParams();

      if (queryOverride.trim()) {
        params.append("q", queryOverride.trim());
      }

      if (locationOverride.trim()) {
        params.append(
          "location",
          locationOverride.trim()
        );
      }

      const queryString = params.toString();

      const url = queryString
        ? `${API_URL}/api/jobs?${queryString}`
        : `${API_URL}/api/jobs`;

      const response = await fetch(url);

      if (!response.ok) {
        throw new Error("Unable to load jobs.");
      }

      const data = await response.json();

      setJobs(
        Array.isArray(data.jobs)
          ? data.jobs
          : []
      );

      setLastUpdated(new Date());
    } catch (err) {
      console.error("Jobs loading error:", err);
    } finally {
      setLoadingJobs(false);
    }
  };

  // ============================================================
  // INITIAL JOB LOAD + AUTO REFRESH
  // ============================================================

  useEffect(() => {
    loadJobs();

    const intervalId = setInterval(() => {
      loadJobs(searchTerm, locationTerm);
    }, AUTO_REFRESH_INTERVAL_MS);

    return () => clearInterval(intervalId);

    // We intentionally run this effect only once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ============================================================
  // JOB SEARCH
  // ============================================================

  const handleLocationSearch = () => {
    loadJobs(searchTerm, locationTerm);
  };

  const handleManualRefresh = () => {
    loadJobs(searchTerm, locationTerm);
  };

  // ============================================================
  // LAST UPDATED
  // ============================================================

  const formatLastUpdated = () => {
    if (!lastUpdated) {
      return "";
    }

    return lastUpdated.toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  // ============================================================
  // FILE SELECTION
  // ============================================================

  const handleFileChange = (event) => {
    const file = event.target.files?.[0];

    setError("");
    setResult(null);

    if (!file) {
      setSelectedFile(null);
      return;
    }

    // Check PDF
    if (
      file.type !== "application/pdf" &&
      !file.name.toLowerCase().endsWith(".pdf")
    ) {
      setError("Please select a PDF resume.");
      setSelectedFile(null);
      return;
    }

    // Check size
    if (file.size > 10 * 1024 * 1024) {
      setError(
        "Resume must be smaller than 10 MB."
      );
      setSelectedFile(null);
      return;
    }

    setSelectedFile(file);
  };

  // ============================================================
  // UPLOAD & ANALYZE RESUME
  // ============================================================

  const handleUpload = async () => {
    if (!selectedFile) {
      setError("Please choose your resume first.");
      return;
    }

    setUploading(true);
    setError("");
    setResult(null);

    const formData = new FormData();

    formData.append("file", selectedFile);

    try {
      const response = await fetch(
        `${API_URL}/api/resume/upload`,
        {
          method: "POST",
          body: formData,
        }
      );

      let data;

      try {
        data = await response.json();
      } catch {
        throw new Error(
          "The server returned an invalid response."
        );
      }

      if (!response.ok) {
        throw new Error(
          typeof data.detail === "string"
            ? data.detail
            : "Resume analysis failed."
        );
      }

      console.log(
        "Resume analysis response:",
        data
      );

      setResult(data);

      setActivePage("dashboard");
    } catch (err) {
      console.error("Upload error:", err);

      setError(
        err.message ||
          "Unable to connect to the backend."
      );
    } finally {
      setUploading(false);
    }
  };

  // ============================================================
  // RE-ANALYZE
  // ============================================================

  const handleReanalyze = () => {
    setResult(null);
    setSelectedFile(null);
    setError("");
    setActivePage("home");
  };

  // ============================================================
  // JOB MODAL
  // ============================================================

  const openJob = (job) => {
    setSelectedJob(job);
  };

  const closeJob = () => {
    setSelectedJob(null);
  };

  // ============================================================
  // APPLY
  // ============================================================

  const handleApply = () => {
    if (selectedJob?.apply_url) {
      window.open(
        selectedJob.apply_url,
        "_blank",
        "noopener,noreferrer"
      );
    } else {
      alert(
        "No application link is available for this listing."
      );
    }
  };

  // ============================================================
  // FILTER JOBS
  // ============================================================

  const filteredJobs = jobs.filter((job) => {
    const search = searchTerm
      .toLowerCase()
      .trim();

    const title =
      job.title?.toLowerCase() || "";

    const company =
      job.company?.toLowerCase() || "";

    const skills = Array.isArray(job.skills)
      ? job.skills
      : [];

    const matchesSearch =
      !search ||
      title.includes(search) ||
      company.includes(search) ||
      skills.some((skill) =>
        String(skill)
          .toLowerCase()
          .includes(search)
      );

    const matchesType =
      jobType === "All" ||
      job.type === jobType;

    return matchesSearch && matchesType;
  });

  // ============================================================
  // AI ANALYSIS
  // ============================================================

  const analysis = result?.analysis || {};

  // ============================================================
  // MATCH LABEL
  // ============================================================

  const getMatchLabel = (score) => {
    const numericScore = Number(score) || 0;

    if (numericScore >= 90) {
      return "Excellent Match";
    }

    if (numericScore >= 75) {
      return "Strong Match";
    }

    if (numericScore >= 60) {
      return "Good Match";
    }

    return "Potential Match";
  };

  // ============================================================
  // HOME PAGE
  // ============================================================

  const renderHome = () => (
    <main className="hero">
      <div className="hero-content">

        <div className="badge">
          AI-Powered Career Intelligence
        </div>

        <h1>
          Find Jobs That
          <br />
          <span>Match You.</span>
        </h1>

        <p className="hero-description">
          Upload your resume and let AI discover
          relevant opportunities, analyze your
          compatibility, identify skill gaps, and
          build your personalized career roadmap.
        </p>

        <div className="upload-section">

          <label className="file-box">

            <div className="upload-icon">
              📄
            </div>

            <div className="file-info">

              <strong>
                {selectedFile
                  ? selectedFile.name
                  : "Choose your resume"}
              </strong>

              <small>
                PDF files only • Maximum 10 MB
              </small>

            </div>

            <input
              type="file"
              accept=".pdf,application/pdf"
              onChange={handleFileChange}
            />

          </label>

          <button
            className="upload-button"
            onClick={handleUpload}
            disabled={uploading}
          >
            {uploading
              ? "Analyzing Resume..."
              : "Analyze Resume"}
          </button>

        </div>

        {error && (
          <div className="error-message">
            ❌ {error}
          </div>
        )}

        <div className="home-features">

          <div className="home-feature">
            <span>📄</span>
            <strong>Resume Analysis</strong>
            <small>
              Extract skills and experience
            </small>
          </div>

          <div className="home-feature">
            <span>🎯</span>
            <strong>Smart Matching</strong>
            <small>
              Find suitable opportunities
            </small>
          </div>

          <div className="home-feature">
            <span>📊</span>
            <strong>Skill Gaps</strong>
            <small>
              Know what to improve
            </small>
          </div>

          <div className="home-feature">
            <span>🗺️</span>
            <strong>Career Roadmap</strong>
            <small>
              Build your career path
            </small>
          </div>

        </div>

        <div className="status">
          Backend status:{" "}

          <strong
            className={
              backendStatus === "healthy"
                ? "status-online"
                : backendStatus === "offline"
                ? "status-offline"
                : ""
            }
          >
            {backendStatus}
          </strong>
        </div>

      </div>
    </main>
  );

  // ============================================================
  // JOBS PAGE
  // ============================================================

  const renderJobs = () => (
    <main className="jobs-page">

      <div className="jobs-container">

        <div className="page-heading">

          <div className="badge">
            AI-Powered Job Discovery
          </div>

          <h1>
            Find Your Next
            <span> Opportunity.</span>
          </h1>

          <p>
            Explore jobs and internships matched
            to your skills and career goals.
          </p>

        </div>

        <div className="job-filters">

          <input
            type="text"
            placeholder="Search jobs, companies or skills..."
            value={searchTerm}
            onChange={(event) =>
              setSearchTerm(event.target.value)
            }
          />

          <input
            type="text"
            placeholder="Location (e.g. Bengaluru, Mumbai, Remote)"
            value={locationTerm}
            onChange={(event) =>
              setLocationTerm(event.target.value)
            }
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                handleLocationSearch();
              }
            }}
          />

          <select
            value={jobType}
            onChange={(event) =>
              setJobType(event.target.value)
            }
          >
            <option value="All">
              All Job Types
            </option>

            <option value="Internship">
              Internship
            </option>

            <option value="Full-time">
              Full-time
            </option>
          </select>

          <button
            className="location-search-button"
            onClick={handleLocationSearch}
          >
            Search
          </button>

        </div>

        <div className="job-count-row">

          <div className="job-count">
            {loadingJobs
              ? "Loading jobs..."
              : `${filteredJobs.length} jobs available`}
          </div>

          <div className="job-refresh">

            {lastUpdated && (
              <span className="last-updated">
                Updated at{" "}
                {formatLastUpdated()}
              </span>
            )}

            <button
              className="refresh-button"
              onClick={handleManualRefresh}
              disabled={loadingJobs}
            >
              {loadingJobs
                ? "Refreshing..."
                : "🔄 Refresh"}
            </button>

          </div>

        </div>

        <div className="jobs-grid">

          {filteredJobs.map((job) => {

            const skills = Array.isArray(
              job.skills
            )
              ? job.skills
              : [];

            return (
              <div
                className="job-card"
                key={
                  job.id ||
                  job.job_id ||
                  `${job.title}-${job.company}`
                }
              >

                <div className="job-card-top">

                  <div className="company-icon">
                    {job.company
                      ?.charAt(0)
                      .toUpperCase() || "J"}
                  </div>

                  <div>

                    <h3>
                      {job.title}
                    </h3>

                    <p>
                      {job.company}
                    </p>

                  </div>

                </div>

                <div className="job-info">
                  📍 {job.location}
                  {" • "}
                  💼 {job.type}
                </div>

                <p className="job-description">
                  {job.description}
                </p>

                <div className="job-dates">

                  <span>
                    🕒 {job.posted_label}
                  </span>

                  <span>
                    ⏳ Apply by:{" "}
                    {job.apply_by_label}
                  </span>

                </div>

                <div className="job-card-skills">

                  {skills
                    .slice(0, 5)
                    .map((skill, index) => (
                      <span key={index}>
                        {skill}
                      </span>
                    ))}

                  {skills.length > 5 && (
                    <span>
                      +{skills.length - 5}
                    </span>
                  )}

                </div>

                <button
                  className="view-job-button"
                  onClick={() => openJob(job)}
                >
                  View Job Details →
                </button>

              </div>
            );
          })}

        </div>

        {!loadingJobs &&
          filteredJobs.length === 0 && (
            <div className="no-jobs">
              No jobs found.
            </div>
          )}

      </div>

    </main>
  );

  // ============================================================
  // JOB DETAILS MODAL
  // ============================================================

  const renderJobDetails = () => {

    if (!selectedJob) {
      return null;
    }

    const skills = Array.isArray(
      selectedJob.skills
    )
      ? selectedJob.skills
      : [];

    return (
      <div
        className="modal-overlay"
        onClick={closeJob}
      >

        <div
          className="job-modal"
          onClick={(event) =>
            event.stopPropagation()
          }
        >

          <button
            className="close-button"
            onClick={closeJob}
          >
            ×
          </button>

          <div className="company-icon large">
            {selectedJob.company
              ?.charAt(0)
              .toUpperCase() || "J"}
          </div>

          <h2>
            {selectedJob.title}
          </h2>

          <p className="modal-company">
            {selectedJob.company}
          </p>

          <div className="job-info">
            📍 {selectedJob.location}
            {" • "}
            💼 {selectedJob.type}
          </div>

          <div className="job-dates">

            <span>
              🕒 {selectedJob.posted_label}
            </span>

            <span>
              ⏳ Apply by:{" "}
              {selectedJob.apply_by_label}
            </span>

          </div>

          <div className="modal-section">

            <h3>
              Job Description
            </h3>

            <p>
              {selectedJob.description}
            </p>

          </div>

          <div className="modal-section">

            <h3>
              Required Skills
            </h3>

            <div className="skills-container">

              {skills.map(
                (skill, index) => (
                  <span
                    className="skill-badge"
                    key={index}
                  >
                    {skill}
                  </span>
                )
              )}

            </div>

          </div>

          <button
            className="apply-button"
            onClick={handleApply}
          >
            Apply Now →
          </button>

        </div>

      </div>
    );
  };

  // ============================================================
  // ABOUT DETAIL MODAL
  // ============================================================

  const renderAboutDetails = () => {

    if (!selectedAbout) {
      return null;
    }

    return (
      <div
        className="modal-overlay"
        onClick={() =>
          setSelectedAbout(null)
        }
      >

        <div
          className="job-modal"
          onClick={(event) =>
            event.stopPropagation()
          }
        >

          <button
            className="close-button"
            onClick={() =>
              setSelectedAbout(null)
            }
          >
            ×
          </button>

          <div className="company-icon large">
            {selectedAbout.icon}
          </div>

          <h2>
            {selectedAbout.title}
          </h2>

          <p className="modal-company">
            {selectedAbout.summary}
          </p>

          <div className="modal-section">

            <h3>
              What it does
            </h3>

            <ul className="about-detail-list">

              {selectedAbout.points.map(
                (point, index) => (
                  <li key={index}>
                    {point}
                  </li>
                )
              )}

            </ul>

          </div>

        </div>

      </div>
    );
  };

  // ============================================================
  // DASHBOARD
  // ============================================================

  const renderDashboard = () => {

    const topJobs =
      Array.isArray(result?.job_matches)
        ? result.job_matches.slice(0, 3)
        : [];

    const skillGaps =
      Array.isArray(analysis.skill_gaps)
        ? analysis.skill_gaps
        : [];

    const roadmap =
      Array.isArray(analysis.career_roadmap)
        ? analysis.career_roadmap
        : [];

    const skills =
      Array.isArray(analysis.skills)
        ? analysis.skills
        : [];

    return (
      <main className="dashboard-page">

        <div className="dashboard-container">

          <div className="page-heading">

            <div className="badge">
              Career Intelligence
            </div>

            <h1>
              Your Career
              <span> Dashboard.</span>
            </h1>

            <p>
              Track your resume profile, skills,
              job matches and career development.
            </p>

          </div>

          {!result ? (

            <div className="dashboard-empty">

              <div className="empty-icon">
                📄
              </div>

              <h2>
                Analyze your resume first
              </h2>

              <p>
                Upload your resume from the home
                page to generate your personalized
                career dashboard.
              </p>

              <button
                className="upload-button"
                onClick={() =>
                  setActivePage("home")
                }
              >
                Analyze Resume
              </button>

            </div>

          ) : (

            <>

              <div className="dashboard-stats">

                <div className="stat-card">

                  <strong>
                    {analysis.experience_level ||
                      "Fresher"}
                  </strong>

                  <span>
                    Experience Level
                  </span>

                </div>

                <div className="stat-card">

                  <strong>
                    {skills.length}
                  </strong>

                  <span>
                    Skills Identified
                  </span>

                </div>

                <div className="stat-card">

                  <strong>
                    {Array.isArray(
                      result.job_matches
                    )
                      ? result.job_matches.length
                      : 0}
                  </strong>

                  <span>
                    Job Matches
                  </span>

                </div>

                <div className="stat-card">

                  <strong>
                    {result.job_matches?.[0]
                      ?.match_score || 0}
                    %
                  </strong>

                  <span>
                    Best Match
                  </span>

                </div>

              </div>

              {analysis.candidate_summary && (

                <section className="dashboard-section">

                  <h2>
                    👤 Candidate Profile
                  </h2>

                  <p className="dashboard-summary">
                    {analysis.candidate_summary}
                  </p>

                </section>

              )}

              <section className="dashboard-section">

                <div className="section-header">

                  <div>

                    <h2>
                      🎯 Top Job Matches
                    </h2>

                    <p>
                      Opportunities with the highest
                      compatibility with your profile.
                    </p>

                  </div>

                  <button
                    className="secondary-button"
                    onClick={() =>
                      setActivePage("jobs")
                    }
                  >
                    View All Jobs →
                  </button>

                </div>

                <div className="dashboard-jobs">

                  {topJobs.length > 0 ? (

                    topJobs.map(
                      (job, index) => (

                        <div
                          className="dashboard-job"
                          key={
                            job.job_id ||
                            `${job.title}-${job.company}-${index}`
                          }
                        >

                          <div className="dashboard-job-info">

                            <span className="dashboard-rank">
                              #{index + 1}
                            </span>

                            <div>

                              <strong>
                                {job.title}
                              </strong>

                              <p>
                                {job.company}
                              </p>

                            </div>

                          </div>

                          <div className="dashboard-score">

                            <strong>
                              {job.match_score}%
                            </strong>

                            <small>
                              {getMatchLabel(
                                job.match_score
                              )}
                            </small>

                          </div>

                        </div>

                      )
                    )

                  ) : (

                    <p>
                      No matching jobs found yet.
                    </p>

                  )}

                </div>

              </section>

              <section className="dashboard-section">

                <h2>
                  📊 Skills to Develop
                </h2>

                {skillGaps.length > 0 ? (

                  <div className="skills-container">

                    {skillGaps.map(
                      (gap, index) => (

                        <span
                          className="skill-badge missing"
                          key={index}
                        >
                          {gap}
                        </span>

                      )
                    )}

                  </div>

                ) : (

                  <p>
                    Great! No major skill gaps
                    were identified.
                  </p>

                )}

              </section>

              <section className="dashboard-section">

                <h2>
                  🗺️ Career Roadmap
                </h2>

                {roadmap.length > 0 ? (

                  <div className="roadmap">

                    {roadmap.map(
                      (step, index) => (

                        <div
                          className="roadmap-step"
                          key={index}
                        >

                          <div className="roadmap-number">
                            {index + 1}
                          </div>

                          <div className="roadmap-content">

                            <p>
                              {step}
                            </p>

                          </div>

                        </div>

                      )
                    )}

                  </div>

                ) : (

                  <p>
                    Your personalized roadmap
                    will appear here.
                  </p>

                )}

              </section>

              <div className="dashboard-actions">

                <button
                  className="upload-button"
                  onClick={handleReanalyze}
                >
                  Analyze Another Resume
                </button>

                <button
                  className="secondary-button"
                  onClick={() =>
                    setActivePage("jobs")
                  }
                >
                  Explore Jobs →
                </button>

              </div>

            </>

          )}

        </div>

      </main>
    );
  };

  // ============================================================
  // ABOUT PAGE
  // ============================================================

  const renderAbout = () => (
    <main className="about-page">

      <div className="about-container">

        <div className="page-heading">

          <div className="badge">
            About JobMatch AI
          </div>

          <h1>
            Your Resume.
            <br />
            Your{" "}
            <span>
              Career Intelligence.
            </span>
          </h1>

          <p>
            JobMatch AI is an AI-powered career
            assistant designed to help students
            and freshers discover suitable
            opportunities based on their skills,
            projects and career goals.
          </p>

        </div>

        <div className="about-grid">

          <div
            className="about-card"
            onClick={() =>
              setSelectedAbout(
                ABOUT_DETAILS.resume
              )
            }
          >

            <div className="about-icon">
              📄
            </div>

            <h3>
              Resume Analysis
            </h3>

            <p>
              Upload your resume and extract
              important information such as skills,
              education, projects and technical
              experience.
            </p>

            <span className="about-card-link">
              Learn more →
            </span>

          </div>

          <div
            className="about-card"
            onClick={() =>
              setSelectedAbout(
                ABOUT_DETAILS.matching
              )
            }
          >

            <div className="about-icon">
              🎯
            </div>

            <h3>
              Smart Job Matching
            </h3>

            <p>
              Compare your skills with job
              requirements and rank opportunities
              according to compatibility.
            </p>

            <span className="about-card-link">
              Learn more →
            </span>

          </div>

          <div
            className="about-card"
            onClick={() =>
              setSelectedAbout(
                ABOUT_DETAILS.gaps
              )
            }
          >

            <div className="about-icon">
              📊
            </div>

            <h3>
              Skill Gap Detection
            </h3>

            <p>
              Identify missing skills that can
              improve your chances of getting
              selected for specific roles.
            </p>

            <span className="about-card-link">
              Learn more →
            </span>

          </div>

          <div
            className="about-card"
            onClick={() =>
              setSelectedAbout(
                ABOUT_DETAILS.roadmap
              )
            }
          >

            <div className="about-icon">
              🗺️
            </div>

            <h3>
              Career Roadmap
            </h3>

            <p>
              Get personalized recommendations
              for improving your technical profile
              and preparing for future opportunities.
            </p>

            <span className="about-card-link">
              Learn more →
            </span>

          </div>

        </div>

        <section className="about-how">

          <h2>
            How JobMatch AI Works
          </h2>

          <div className="how-steps">

            <div className="how-step">

              <span>01</span>

              <h3>
                Upload Resume
              </h3>

              <p>
                Upload your PDF resume.
              </p>

            </div>

            <div className="flow-arrow">
              →
            </div>

            <div className="how-step">

              <span>02</span>

              <h3>
                AI Analysis
              </h3>

              <p>
                Extract and understand your profile.
              </p>

            </div>

            <div className="flow-arrow">
              →
            </div>

            <div className="how-step">

              <span>03</span>

              <h3>
                Match Jobs
              </h3>

              <p>
                Compare your skills with available jobs.
              </p>

            </div>

            <div className="flow-arrow">
              →
            </div>

            <div className="how-step">

              <span>04</span>

              <h3>
                Improve
              </h3>

              <p>
                Follow your personalized career roadmap.
              </p>

            </div>

          </div>

        </section>

      </div>

    </main>
  );

  // ============================================================
  // MAIN UI
  // ============================================================

  return (
    <div className="app">

      {/* ======================================================
          NAVBAR
      ====================================================== */}

      <nav className="navbar">

        <div
          className="logo"
          onClick={() =>
            setActivePage("home")
          }
        >

          <svg
            className="logo-icon"
            viewBox="0 0 40 40"
            xmlns="http://www.w3.org/2000/svg"
          >

            <rect
              width="40"
              height="40"
              rx="11"
              fill="#4f46e5"
            />

            <path
              d="M13 16.5C13 14.567 14.567 13 16.5 13H23.5C25.433 13 27 14.567 27 16.5V17.5H30C30.5523 17.5 31 17.9477 31 18.5V26.5C31 27.8807 29.8807 29 28.5 29H11.5C10.1193 29 9 27.8807 9 26.5V18.5C9 17.9477 9.44772 17.5 10 17.5H13V16.5Z"
              fill="white"
            />

            <path
              d="M16.5 15C15.6716 15 15 15.6716 15 16.5V17.5H25V16.5C25 15.6716 24.3284 15 23.5 15H16.5Z"
              fill="#4f46e5"
            />

            <rect
              x="18"
              y="21"
              width="4"
              height="3"
              rx="1"
              fill="#4f46e5"
            />

          </svg>

          <span className="logo-text">
            JobMatch AI
          </span>

        </div>

        <div className="nav-links">

          <span
            className={
              activePage === "jobs"
                ? "active-nav"
                : ""
            }
            onClick={() =>
              setActivePage("jobs")
            }
          >
            Jobs
          </span>

          <span
            className={
              activePage === "dashboard"
                ? "active-nav"
                : ""
            }
            onClick={() =>
              setActivePage("dashboard")
            }
          >
            Dashboard
          </span>

          <span
            className={
              activePage === "about"
                ? "active-nav"
                : ""
            }
            onClick={() =>
              setActivePage("about")
            }
          >
            About
          </span>

        </div>

      </nav>

      {/* ======================================================
          PAGES
      ====================================================== */}

      {activePage === "home" &&
        renderHome()}

      {activePage === "jobs" &&
        renderJobs()}

      {activePage === "dashboard" &&
        renderDashboard()}

      {activePage === "about" &&
        renderAbout()}

      {/* ======================================================
          MODALS
      ====================================================== */}

      {renderJobDetails()}

      {renderAboutDetails()}

    </div>
  );
}

export default App;